name: docs
# either manually started, or on a schedule
on: [ push, workflow_dispatch ]
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  docs:
    # ubuntu
    runs-on: ubuntu-latest
    steps:
    # need the repo checked out
    - name: checkout repo
      uses: actions/checkout@v3

    # need python
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: pip install requests PyYAML

    # Scala to ruh Chisel
    - name: Install Scala
      uses: olafurpg/setup-scala@v10
      with:
        java-version: openjdk@1.11

      # Generate Verilog from Chisel code
    - name: Generate Verilog
      run: sbt "runMain TweezersGenerator"

    # fetch the Verilog from Wokwi API
    - name: fetch Verilog and build config
      run: ./configure.py --check-docs

    # make an artifact
    - name: upload artifact
      uses: actions/upload-artifact@v3
      with:
          name: docs
          path: info.yaml
